@startuml
title Ввод треугольников из файла

start

:Открыть файл;
if (ОШИБКА?) then (yes)
    :Вывести сообщение об ошибке;
    stop
else (no)
    :Прочитать длины сторон
    текущего треугольника
    из файла;
    while (В файле еще есть непрочитанные данные?)
      :Прочитать следующий
      треугольник из файла;
      if (Найдено не-числовое значение в файле?) then (yes)
          :Вывести сообщение об ошибке;
          :Выход;
          stop
      else if (Треугольник существует?) then (yes)
          if (Треугольник прямоугольный?) then (yes)
              :Вычислить площадь;
              :Добавление вектора
              длины сторон и площади
              вектора треугольников;
              :Вычислить общую площадь
              прямоугольных треугольников;
              :Вывод суммарной площади;
          else (no)
              :Добавление вектора
              длины сторон
              и нулевой площади
              вектора треугольников;
          endif
      else (no)
          :Пропустить неверный ввод;
      endif
      :Продолжить;
    endwhile
        :Выход;
        stop
endif

@enduml
