@startuml
title Ручной ввод треугольников

start

:Ввести количество треугольников;
if (Некорректные данные?) then (yes)
    :Вывести сообщение об ошибке;
    :Сброс ошибки ввода;
    :Пропустить направильный ввод;
else (no)
    :Продолжить;
endif

while (Есть еще треугольники?) is (yes)
    :Ввести длины сторон
    текущего треугольника;
    if (Некорректные данные?) then (yes)
        :Вывести сообщение об ошибке;
        :Сброс ошибки ввода;
        :Вернуться
        на предыдущий шаг;
    else if (Треугольник существует?) then (yes)
        if (Треугольник прямоугольный?) then (yes)
            :Вычисление площади;
            :Добавление вектора
            длины сторон
            и площади вектора
            треугольников;
            :Вычислить общую площадь
            прямоугольных треугольников;
            :Вывод суммарной площади;
        else (no)
            :Добавление вектора
            длины сторон
            и нулевой площади
            вектора треугольников;
        endif
    else (no)
        :Вернуться
        на предыдущий шаг;
    endif
endwhile

stop

@enduml
