@startuml
title Вывод информации о треугольниках

start
:Инициализировать суммарную площадь и общее количество прямоугольных треугольников;
:Вывести заголовок данных о треугольниках;
:i = 0;
while (i < triangles.size() ?)
    :Вывести информацию о текущем треугольнике (стороны и площадь, если треугольник прямоугольный);
    if (Текущий треугольник прямоугольный?) then (yes)
        :Добавить его площадь в суммарную площадь;
        :Добавить его в общее количество прямоугольных треугольников;
        :Вывести текущую суммарную площадь прямоугольных треугольников и кол-во прямоугольных треугольников;
    endif
    :i++;
endwhile
:Вывести окончательную суммарную площадь прямоугольных треугольников и кол-во прямоугольных треугольников;
stop
@enduml
