@startuml
title Генерация случайных треугольников

start
:Инициализировать пустой вектор треугольников;
:i = 0;
while (i < count ?)
    :Сгенерировать случайные значения длин сторон треугольника;
    if (Треугольник прямоугольный?) then (yes)
        :Вычислить его площадь;
        :Добавить треугольник в вектор треугольников с площадью;
        :Вычислить суммарную площадь всех треугольников;
    else (no)
        :Добавить треугольник в вектор треугольников с нулевой площадью;
    endif
    :i++;
endwhile
:Вернуть вектор треугольников;
stop
@enduml
