@startuml
title Интерфейс программы

start

:Выбрать один из вариантов;
if (1 ввести данные вручную?) then (yes)
    :Ввести количество треугольников;
    :Ввести длины сторон
    каждого треугольника;
else if (2 ввести данные из файла?) then (yes)
    :Ввести путь к файлу;
    if (Файл существует?) then (yes)
        :Прочитать данные о треугольниках;
    else (no)
        :Вывести сообщение об ошибке
        и завершить программу;
        stop
    endif
else if (3 сгенерировать данные?) then (yes)
    :Ввести количество треугольников;
    :Ввести минимальную
    и максимальную длину стороны;
    :Генерировать треугольники;
endif
:Вычислить и вывести результат;
stop
@enduml
